var stockApps = [
  { name: "Weather", id: "com.apple.weather" },
  { name: "App Store", id: "com.apple.AppStore" },
  { name: "Apple Watch", id: "com.apple.Bridge" },
  { name: "Apple TV", id: "com.apple.tv" },
  { name: "Calculator", id: "com.apple.calculator" },
  { name: "Calendar", id: "com.apple.mobilecal" },
  { name: "Camera", id: "com.apple.camera" },
  { name: "Classroom", id: "com.apple.classroom" },
  { name: "Clock", id: "com.apple.mobiletimer" },
  { name: "Compass", id: "com.apple.compass" },
  { name: "Contacts", id: "com.apple.MobileAddressBook" },
  { name: "FaceTime", id: "com.apple.facetime" },
  { name: "Files", id: "com.apple.DocumentsApp" },
  { name: "Game Center", id: "com.apple.gamecenter" },
  { name: "Health", id: "com.apple.Health" },
  { name: "Home", id: "com.apple.Home" },
  { name: "iBooks", id: "com.apple.iBooks" },
  { name: "iTunes Store", id: "com.apple.MobileStore" },
  { name: "Mail", id: "com.apple.mobilemail" },
  { name: "Maps", id: "com.apple.Maps" },
  { name: "Measure", id: "com.apple.measure" },
  { name: "Messages", id: "com.apple.MobileSMS" },
  { name: "Music Memos", id: "com.apple.musicmemos" },
  { name: "Music", id: "com.apple.Music" },
  { name: "News", id: "com.apple.news" },
  { name: "Notes", id: "com.apple.mobilenotes" },
  { name: "Phone", id: "com.apple.mobilephone" },
  { name: "Photo Booth", id: "com.apple.Photo-Booth" },
  { name: "Photos", id: "com.apple.mobileslideshow" },
  { name: "Playgrounds", id: "com.apple.Playgrounds" },
  { name: "Podcasts", id: "com.apple.podcasts" },
  { name: "Reminders", id: "com.apple.reminders" },
  { name: "Safari", id: "com.apple.mobilesafari" },
  { name: "Settings", id: "com.apple.Preferences" },
  { name: "Stocks", id: "com.apple.stocks" },
  { name: "Tips", id: "com.apple.tips" },
  { name: "Trailers", id: "com.apple.movietrailers" },
  { name: "TV", id: "com.apple.tv" },
  { name: "Videos", id: "com.apple.videos" },
  { name: "Voice Memos", id: "com.apple.VoiceMemos" },
  { name: "Wallet", id: "com.apple.Passbook" },
  { name: "Find My", id: "com.apple.findmy" },
  { name: "Find Friends", id: "com.apple.mobileme.fmf1" },
  { name: "Feedback Assistant", id: "com.apple.appleseed.FeedbackAssistant" },
  { name: "Find My iPhone", id: "com.apple.mobileme.fmip1" },
  { name: "Translate", id: "com.apple.Translate" },
];

var jailbreakApps = [
  { name: "Cydia", id: "com.saurik.Cydia" },
  { name: "Filza", id: "com.tigisoftware.Filza" },
  { name: "Substitute", id: "com.ex.substiture.settings" },
  { name: "Unc0ver", id: "science.xnu.undecimus" },
  { name: "AltStore", id: "com.rileytestut.AltStore" },
  { name: "NewTerm", id: "ws.hbang.Terminal" },
  { name: "Electra", id: "org.coolstar.electra" },
  { name: "Taurine", id: "com.odysseyteam.taurine" },
  { name: "Sileo", id: "org.coolstar.sileo" },
  { name: "Dra1n", id: "com.amywhile.dra1n-fix" },
  { name: "Cr4shed", id: "com.muirey03.cr4shedgui" },
  { name: "iCleaner", id: "com.ivanobilenchi.icleaner" },
  { name: "BundleIDsXII", id: "de.mass1veerr0r.bundleidsxii" },
  { name: "ReProvision", id: "jp.soh.reprovision.ios" },
  { name: "Snowboard", id: "com.spark.snowboardapplication" },
  { name: "LibHooker", id: "org.coolstar.libhooker" },
  { name: "Zebra", id: "xyz.willy.Zebra" },
  { name: "Chimera", id: "com.electrateam.chimera" },
  { name: "iSecureOS", id: "com.geosn0w.iSecureOS" },
  { name: "TSS Saver", id: "co.dynastic.tsssaver" },
  { name: "Bundley", id: "com.spark.bundley" },
  { name: "Flex 3", id: "com.johncoates.Flex" },
];

var prefs = [
  { name: "Airplane Mode", id: "AirplaneMode" },
  { name: "Wi-Fi", id: "WiFi" },
  { name: "Bluetooth", id: "Bluetooth" },
  { name: "Mobile Data", id: "CellularData" },
  { name: "Personal Hotspot", id: "PersonalHotspot" },
  { name: "Carrier", id: "CarrierSettings" },
  { name: "Cellular", id: "Carrier" },
  { name: "VPN", id: "VPN" },
  {},
  { name: "Notifications", id: "NotificationCenter" },
  { name: "Sounds & Haptics", id: "Sounds" },
  { name: "Do Not Disturb", id: "DND" },
  { name: "Screen Time", id: "ScreenTime" },
  {},
  { name: "General", id: "General" },
  { name: "Control Centre", id: "ControlCenter" },
  { name: "Display & Brightness", id: "Display" },
  { name: "Home Screen", id: "" },
  { name: "Accessibility", id: "Accessibility" },
  { name: "Wallpaper", id: "Wallpaper" },
  { name: "Siri & Search", id: "Siri" },
  { name: "Face ID & Passcode", id: "PearlID-D22" },
  { name: "Touch ID & Passcode", id: "TouchID" },
  { name: "Passcode", id: "Passcode" },
  { name: "Emergency SOS", id: "SOS" },
  { name: "Exposure Notifications", id: "" },
  { name: "Battery", id: "BatteryUsage" },
  { name: "Privacy", id: "Privacy" },
  { name: "Microphone", id: "Microphone" },
  { name: "Location", id: "Location" },
  { name: "Speech Recognition", id: "SpeecRecognition" },
  {},
  { name: "App Store", id: "AppStore" },
  { name: "Wallet & Apple Pay", id: "Wallet" },
  { name: "Passbook", id: "Passbook" },
  {},
  { name: "Passwords", id: "Passwords" },
  { name: "Accounts & Passwords", id: "KeychainSync" },
  { name: "Accounts & Passwords", id: "PasswordAutoFill" },
  { name: "Mail", id: "Mail" },
  { name: "Contacts", id: "Contacts" },
  { name: "Compass", id: "Compass" },
  { name: "Calendar", id: "Calendar" },
  { name: "Notes", id: "Notes" },
  { name: "Reminders", id: "Reminders" },
  { name: "Voice Memos", id: "VoiceMemos" },
  { name: "Phone", id: "Phone" },
  { name: "Messages", id: "Messages" },
  { name: "FaceTime", id: "FaceTime" },
  { name: "Safari", id: "Safari" },
  { name: "Stocks", id: "Stocks" },
  { name: "News", id: "News" },
  { name: "Translate", id: "Translate" },
  { name: "TV", id: "TVApp" },
  { name: "Shortcuts", id: "Shortcuts" },
  { name: "Health", id: "Health" },
  { name: "Home", id: "HomeData" },
  { name: "Measure", id: "Measure" },
  { name: "Maps", id: "Maps" },
  { name: "Music", id: "Music" },
  { name: "Music", id: "MediaLibrary" },
  {},
  { name: "Nike+", id: "Victoria" },
  { name: "Activity", id: "Motion" },
  {},
  { name: "iCloud", id: "iCloud" },
  { name: "iTunes", id: "iTunes" },
  { name: "iBooks", id: "iBooks" },
  {},
  { name: "Twitter", id: "Twitter" },
  { name: "Facebook", id: "FacebookSettings" },
  { name: "Flickr", id: "FlickrSettings" },
  { name: "Vimeo", id: "VimeoSettings" },
  { name: "Weibo", id: "TencentWeiboSettings" },
  {},
  { name: "Photos", id: "Photos" },
  { name: "Camera", id: "Camera" },
  { name: "Game Center", id: "GameCenter" },
];

// sorts lists alphabetically
// required in order to label correctly
// probably more efficient to just order them manually in this file as they are static
// but I'm lazy. so if you fancy doing a pull request go ahead :D
stockApps.sort((a, b) => a.name.localeCompare(b.name));
jailbreakApps.sort((a, b) => a.name.localeCompare(b.name));
