var jailbreakApps = [
  { name: "Cydia", id: "com.saurik.Cydia" },
  { name: "Filza", id: "com.tigisoftware.Filza" },
  { name: "Substitute", id: "com.ex.substiture.settings" },
  { name: "Unc0ver", id: "science.xnu.undecimus" },
  { name: "AltStore", id: "com.rileytestut.AltStore" },
  { name: "NewTerm", id: "ws.hbang.Terminal" },
  { name: "Electra", id: "org.coolstar.electra" },
  { name: "Taurine", id: "com.odysseyteam.taurine" },
  { name: "Sileo", id: "org.coolstar.SileoStore" },
  { name: "Dra1n", id: "com.amywhile.dra1n-fix" },
  { name: "Cr4shed", id: "com.muirey03.cr4shedgui" },
  { name: "iCleaner", id: "com.ivanobilenchi.icleaner" },
  { name: "BundleIDsXII", id: "de.mass1veerr0r.bundleidsxii" },
  { name: "ReProvision", id: "jp.soh.reprovision.ios" },
  { name: "Snowboard", id: "com.spark.snowboardapplication" },
  { name: "LibHooker", id: "org.coolstar.libhooker" },
  { name: "Zebra", id: "xyz.willy.Zebra" },
  { name: "Chimera", id: "com.electrateam.chimera" },
  { name: "iSecureOS", id: "com.geosn0w.iSecureOS" },
  { name: "TSS Saver", id: "co.dynastic.tsssaver" },
  { name: "Bundley", id: "com.spark.bundley" },
  { name: "Flex 3", id: "com.johncoates.Flex" },
];
