var prefs = [
  { name: "Airplane Mode", id: "AirplaneMode" },
  { name: "Wi-Fi", id: "WiFi" },
  { name: "Bluetooth", id: "Bluetooth" },
  { name: "Mobile Data", id: "CellularData" },
  { name: "Personal Hotspot", id: "PersonalHotspot" },
  { name: "Carrier", id: "CarrierSettings" },
  { name: "Cellular", id: "Carrier" },
  { name: "VPN", id: "VPN" },
  {},
  { name: "Notifications", id: "NotificationCenter" },
  { name: "Sounds & Haptics", id: "Sounds" },
  { name: "Do Not Disturb", id: "DND" },
  { name: "Screen Time", id: "ScreenTime" },
  {},
  { name: "General", id: "General" },
  { name: "Control Centre", id: "ControlCenter" },
  { name: "Display & Brightness", id: "Display" },
  { name: "Home Screen", id: "HomeScreen" },
  { name: "Accessibility", id: "Accessibility" },
  { name: "Wallpaper", id: "Wallpaper" },
  { name: "Siri & Search", id: "Siri" },
  { name: "Face ID & Passcode", id: "PearlID-D22" },
  { name: "Face ID & Passcode", id: "FaceID" },
  { name: "Touch ID & Passcode", id: "TouchID" },
  { name: "Passcode", id: "Passcode" },
  { name: "Emergency SOS", id: "SOS" },
  { name: "Exposure Notifications", id: "ExposureNotification" },
  { name: "Battery", id: "BatteryUsage" },
  { name: "Privacy", id: "Privacy" },
  { name: "Microphone", id: "Microphone" },
  { name: "Location", id: "Location" },
  { name: "Speech Recognition", id: "SpeecRecognition" },
  {},
  { name: "App Store", id: "AppStore" },
  { name: "Wallet & Apple Pay", id: "Wallet" },
  { name: "Passbook", id: "Passbook" },
  {},
  { name: "Passwords", id: "Passwords" },
  { name: "Accounts & Passwords", id: "KeychainSync" },
  { name: "Accounts & Passwords", id: "PasswordAutoFill" },
  { name: "Mail", id: "Mail" },
  { name: "Contacts", id: "Contacts" },
  { name: "Compass", id: "Compass" },
  { name: "Calendar", id: "Calendar" },
  { name: "Notes", id: "Notes" },
  { name: "Reminders", id: "Reminders" },
  { name: "Voice Memos", id: "VoiceMemos" },
  { name: "Phone", id: "Phone" },
  { name: "Messages", id: "Messages" },
  { name: "FaceTime", id: "FaceTime" },
  { name: "Safari", id: "Safari" },
  { name: "Stocks", id: "Stocks" },
  { name: "News", id: "News" },
  { name: "Translate", id: "Translate" },
  { name: "TV", id: "TVApp" },
  { name: "Shortcuts", id: "Shortcuts" },
  { name: "Health", id: "Health" },
  { name: "Home", id: "HomeData" },
  { name: "Measure", id: "Measure" },
  { name: "Maps", id: "Maps" },
  { name: "Music", id: "Music" },
  { name: "Music", id: "MediaLibrary" },
  {},
  { name: "Nike+", id: "Victoria" },
  { name: "Activity", id: "Motion" },
  {},
  { name: "iCloud", id: "iCloud" },
  { name: "iTunes", id: "iTunes" },
  { name: "iBooks", id: "iBooks" },
  {},
  { name: "Twitter", id: "Twitter" },
  { name: "Facebook", id: "FacebookSettings" },
  { name: "Flickr", id: "FlickrSettings" },
  { name: "Vimeo", id: "VimeoSettings" },
  { name: "Weibo", id: "TencentWeiboSettings" },
  {},
  { name: "Photos", id: "Photos" },
  { name: "Camera", id: "Camera" },
  { name: "Game Center", id: "GameCenter" },
];
