var stockApps = [
  { name: "Weather", id: "com.apple.weather" },
  { name: "App Store", id: "com.apple.AppStore" },
  { name: "Apple Watch", id: "com.apple.Bridge" },
  { name: "Apple TV", id: "com.apple.tv" },
  { name: "Calculator", id: "com.apple.calculator" },
  { name: "Calendar", id: "com.apple.mobilecal" },
  { name: "Camera", id: "com.apple.camera" },
  { name: "Classroom", id: "com.apple.classroom" },
  { name: "Clock", id: "com.apple.mobiletimer" },
  { name: "Compass", id: "com.apple.compass" },
  { name: "Contacts", id: "com.apple.MobileAddressBook" },
  { name: "FaceTime", id: "com.apple.facetime" },
  { name: "Files", id: "com.apple.DocumentsApp" },
  { name: "Game Center", id: "com.apple.gamecenter" },
  { name: "Health", id: "com.apple.Health" },
  { name: "Home", id: "com.apple.Home" },
  { name: "iBooks", id: "com.apple.iBooks" },
  { name: "iTunes Store", id: "com.apple.MobileStore" },
  { name: "Mail", id: "com.apple.mobilemail" },
  { name: "Maps", id: "com.apple.Maps" },
  { name: "Measure", id: "com.apple.measure" },
  { name: "Messages", id: "com.apple.MobileSMS" },
  { name: "Music Memos", id: "com.apple.musicmemos" },
  { name: "Music", id: "com.apple.Music" },
  { name: "News", id: "com.apple.news" },
  { name: "Notes", id: "com.apple.mobilenotes" },
  { name: "Phone", id: "com.apple.mobilephone" },
  { name: "Photo Booth", id: "com.apple.Photo-Booth" },
  { name: "Photos", id: "com.apple.mobileslideshow" },
  { name: "Playgrounds", id: "com.apple.Playgrounds" },
  { name: "Podcasts", id: "com.apple.podcasts" },
  { name: "Reminders", id: "com.apple.reminders" },
  { name: "Safari", id: "com.apple.mobilesafari" },
  { name: "Settings", id: "com.apple.Preferences" },
  { name: "Stocks", id: "com.apple.stocks" },
  { name: "Tips", id: "com.apple.tips" },
  { name: "Trailers", id: "com.apple.movietrailers" },
  { name: "TV", id: "com.apple.tv" },
  { name: "Videos", id: "com.apple.videos" },
  { name: "Voice Memos", id: "com.apple.VoiceMemos" },
  { name: "Wallet", id: "com.apple.Passbook" },
  { name: "Find My", id: "com.apple.findmy" },
  { name: "Find Friends", id: "com.apple.mobileme.fmf1" },
  { name: "Feedback Assistant", id: "com.apple.appleseed.FeedbackAssistant" },
  { name: "Find My iPhone", id: "com.apple.mobileme.fmip1" },
  { name: "Translate", id: "com.apple.Translate" },
];
